// All muscle groups referenced across the exercise dataset (primary + secondary, deduped)
export const muscleGroups = [
  'abductors',
  'abs',
  'adductors',
  'biceps',
  'brachialis',
  'calves',
  'chest',
  'core',
  'forearms',
  'front-delts',
  'full-body',
  'glute-medius',
  'glutes',
  'hamstrings',
  'hip-flexors',
  'lats',
  'lower-back',
  'lower-chest',
  'middle-back',
  'obliques',
  'quadriceps',
  'rear-delts',
  'rotator-cuff',
  'shoulders',
  'side-delts',
  'teres-major',
  'traps',
  'triceps',
  'upper-back',
  'upper-chest',
  'upper-traps',
];

// Consolidated, general-use muscle groups (sub-groups like front/side/rear-delts,
// upper/lower-chest, and back sub-regions rolled up into their parent group)
export const primaryMuscleGroups = [
  'chest',
  'back',
  'shoulders',
  'biceps',
  'triceps',
  'forearms',
  'abs',
  'glutes',
  'quadriceps',
  'hamstrings',
  'calves',
  'full-body',
];

// General tags for labeling a workout (e.g. by split or body region)
export const tags = [
  'push-day',
  'pull-day',
  'legs',
  'upper-body',
  'full-body',
  'chest',
  'back',
  'core',
];

export const equipment = [
  'ab-crunch-machine',
  'ab-wheel',
  'ankle-strap',
  'assisted-pull-up-machine',
  'back-extension-bench',
  'bar',
  'barbell',
  'battle-ropes',
  'bench',
  'box',
  'cable-machine',
  'calf-raise-machine',
  'chest-press-machine',
  'decline-bench',
  'dip-bars',
  'dumbbell',
  'dumbbells',
  'ez-bar',
  'hack-squat-machine',
  'hip-abductor-machine',
  'hip-adductor-machine',
  'incline-bench',
  'kettlebell',
  'kettlebells',
  'landmine-attachment',
  'lat-pulldown-machine',
  'lateral-raise-machine',
  'leg-curl-machine',
  'leg-extension-machine',
  'leg-press-machine',
  'mat',
  'medicine-ball',
  'pec-deck-machine',
  'plate',
  'preacher-bench',
  'pull-up-bar',
  'rings',
  'rope',
  'row-machine',
  'seated-calf-raise-machine',
  'shoulder-press-machine',
  'sled',
  'smith-machine',
  'squat-rack',
  't-bar',
  'trap-bar',
  'wall',
];
export const movementPattern = [
  'anti-extension',
  'anti-lateral-flexion',
  'anti-rotation',
  'chest-adduction',
  'conditioning',
  'elbow-extension',
  'elbow-flexion',
  'full-body',
  'hinge',
  'hip-abduction',
  'hip-adduction',
  'hip-extension',
  'horizontal-abduction',
  'horizontal-pull',
  'horizontal-push',
  'isometric',
  'knee-extension',
  'knee-flexion',
  'loaded-carry',
  'locomotion',
  'lunge',
  'plantar-flexion',
  'power',
  'rotation',
  'scapular-elevation',
  'shoulder-abduction',
  'shoulder-extension',
  'shoulder-flexion',
  'spinal-flexion',
  'squat',
  'vertical-pull',
  'vertical-push',
  'wrist-extension',
  'wrist-flexion',
];
export const bodyRegion = [true, 'core', 'lower-body', 'upper-body'];
export const mechanics = ['pull', 'push', 'static'];
export const exerciseType = ['compound', 'isolation'];
export const trackableMetrics = [
  'addedWeight',
  'assistedWeight',
  'duration',
  'reps',
  'rpe',
  'sets',
  'tempo',
  'weight',
];
