export const dummyWorkoutData: WorkoutSession = {
  _id: '6a077c0a52bb6068b31f31fb',
  userId: '69ac23e42e4d14333eb6acb3',
  name: 'THURSDAY PUSH DAY',
  notes: '',
  location: '',
  tags: ['push', 'upper-body', 'strength'],
  exercises: [
    {
      name: 'Hammer Curl',
      sets: [
        {
          reps: 8,
          weight: 15,
          completed: false,
        },
        {
          reps: 8,
          weight: 15,
          completed: false,
        },
        {
          reps: 8,
          weight: 15,
          completed: false,
        },
      ],
      exerciseDetails: {
        id: 'hammer-curl',
        name: 'Hammer Curl',
        category: 'freeweights',
        exerciseType: 'compound',
        equipment: ['dumbbells'],
        primaryMuscleGroups: ['brachialis', 'biceps'],
        secondaryMuscleGroups: ['forearms'],
        muscleGroups: ['brachialis', 'biceps', 'forearms'],
        movementPattern: 'elbow-flexion',
        bodyRegion: 'upper-body',
        mechanics: 'pull',
        unilateral: false,
        bilateral: true,
        requiresSpotter: false,
        trackableMetrics: ['weight', 'reps', 'sets', 'rpe', 'tempo'],
        defaultRepRange: {
          strength: '1-6',
          hypertrophy: '6-12',
          endurance: '12-25',
        },
        estimatedCaloriesMET: 6,
        aliases: [],
        tags: ['upper-body'],
      },
    },
    {
      name: 'EZ-Bar Curl',
      sets: [
        {
          reps: 8,
          weight: 10,
          completed: false,
        },
        {
          reps: 8,
          weight: 10,
          completed: false,
        },
        {
          reps: 8,
          weight: 10,
          completed: false,
        },
      ],
      exerciseDetails: {
        id: 'ez-bar-curl',
        name: 'EZ-Bar Curl',
        category: 'freeweights',
        exerciseType: 'isolation',
        equipment: ['ez-bar'],
        primaryMuscleGroups: ['biceps'],
        secondaryMuscleGroups: ['brachialis', 'forearms'],
        muscleGroups: ['biceps', 'brachialis', 'forearms'],
        movementPattern: 'elbow-flexion',
        bodyRegion: 'upper-body',
        mechanics: 'pull',
        unilateral: false,
        bilateral: true,
        requiresSpotter: false,
        trackableMetrics: ['weight', 'reps', 'sets', 'rpe', 'tempo'],
        defaultRepRange: {
          strength: '1-6',
          hypertrophy: '6-12',
          endurance: '12-25',
        },
        estimatedCaloriesMET: 6,
        aliases: [],
        tags: ['upper-body'],
      },
    },
  ],
  started: null,
  ended: null,
  baseRoutine: '69ad499a36c805c2482ee432',
  createdAt: '2026-05-15T20:03:23.009Z',
  updatedAt: '2026-05-15T20:03:23.009Z',
};

export const workoutSessionSkeleton: WorkoutSession = {
  _id: 'DEFAULT_WORKOUT',
  name: '',
  userId: '',
  exercises: [],
  started: null,
  ended: null,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  notes: '',
  location: undefined,
  baseRoutine: undefined,
};

export default workoutSessionSkeleton;
